default_language_version:
  python: "python"
default_language_version:
  python: python3.11   # ここはあなたのPythonに合わせて（例：python3.12ならpython3.12）
repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.5
    hooks:
      - id: ruff
